#!/bin/bash

for i in 0 1 2 3 4
do
   python train.py  --fold $i --workers 4  --n-epochs 5  --freeze 1
   python train.py  --fold $i --workers 4  --n-epochs 90

done

#./copy_models

#python predictions.py --fold=-1 --model_type=WindNet

#python evaluation.py