#!/bin/bash

for i in 0 1 2 3 4
do
   python train.py  --batch-size 32 --fold $i --workers 2 --lr 0.0001 --n-epochs 9  --jaccard-weight 1 --freeze 1
   python train.py  --batch-size 32 --fold $i --workers 2 --lr 0.0001 --n-epochs 40  --jaccard-weight 1
   python train.py  --batch-size 32 --fold $i --workers 2 --lr 0.00001 --n-epochs 50 --jaccard-weight 1
   python train.py  --batch-size 32 --fold $i --workers 2 --lr 0.000001 --n-epochs 60 --jaccard-weight 1
done

#./copy_models


#python predictions.py
#python evaluation.py